//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipevideotable
    {
        public int RecipevideoID { get; set; }
        public string Heading { get; set; }
        public string Image { get; set; }
        public string VideoLink { get; set; }
    }
}
